Also add generated source files to src/Makefile.am

diff --git a/.bootstrap-org/generatesource b/.bootstrap-org/generatesource
--- a/.bootstrap-org/generatesource
+++ b/.bootstrap-org/generatesource
@@ -12,6 +12,8 @@ sourceRepository="__sourceRepository__"
 sourceTemplatesDirectory="sourcetemplates"
 headerExtension="__headerExtension__"
 sourceExtension="__sourceExtension__"
+REGEXP_BASE_NAME='[[:alpha:]][[:alnum:]]+'
+REGEXP_BASE_NAME_WHOLE="^$REGEXP_BASE_NAME\$"
 
 printSynopsis() {
 	if test -n "$1"
@@ -19,10 +21,11 @@ printSynopsis() {
 		echo "ERROR:\n\t$1"
 	fi
 	echo "SYNOPSIS"
-	echo "  `basename $0` fileBaseName fileExtension..."
-	echo "  fileBaseName and fileExtension form the new file name(s) based"
-	echo "  on the following patten:"
-	echo "    ./include/${headerSubDir}/fileBaseName.fileExtension"
+	echo "  `basename $0` fileBaseName [-s|--source]"
+	echo "  The command will generate a header file"
+	echo "     fileBaseName.${headerExtension}"
+	echo "  and if -s or --source is given, also a source file"
+	echo "     src/fileBaseName.${sourceExtension}"
 }
 
 # Determine if the value in $1 matches the regular expression in $2.
@@ -57,37 +60,24 @@ then
 	exit 0
 fi
 
-if ! test -n "$2"
-then
-	printSynopsis "Missing argument(s)" >&2
-	exit 1
-fi
-
-if ! validRegExp "$1" '^[[:alpha:]][[:alnum:]]+$' "file base-name"
+if ! validRegExp "$1" "$REGEXP_BASE_NAME_WHOLE" "file base-name"
 then
 	printSynopsis "Invalid file base-name: $1"
 	exit 1
 fi
 
 fileBaseName="$1"
-shift
-fileExtensions=
 
-while [[ "x" != "x$1" ]]
-do
-	extension="$1"
-	shift
-	if [[ "$extension" == "$sourceExtension" ]]
-	then
-		fileExtensions="$fileExtensions $extension"
-	elif [[ "$extension" == "$headerExtension" ]]
-	then
-		fileExtensions="$fileExtensions $extension"
-	else
-		printSynopsis "Invalid file extension: $extension"
-		exit 1
-	fi
-done
+if [[ "x$2" =~ x(-s|--source) ]]
+then
+	fileExtensions="$headerExtension $sourceExtension"
+elif [[ "x$2" == "x" ]]
+then
+	fileExtensions="$headerExtension"
+else
+	echo "Invalid argument: $2"
+	exit 1
+fi
 
 echo "Creating source files based on '$fileBaseName' using extensions $fileExtensions"
 
@@ -114,9 +104,13 @@ replaceExpression()
 	variableToSubstitute="$1"
 	substituteValue=`echo "$2" | sed -r "$r1" | sed -r "$r2" `
 
-	expr="s/__${variableToSubstitute}__/$substituteValue/g"
+	if [[ "x$3" != "xNoUnderscores" ]]
+	then
+		expr="s/__${variableToSubstitute}__/$substituteValue/g"
+	else
+		expr="s/${variableToSubstitute}/$substituteValue/g"
+	fi
 
-	#echo "$expr" >&2
 	echo "$expr"
 }
 
@@ -141,6 +135,16 @@ headerFileName="$fileBaseName.$headerExtension"
 sourceFileName="$fileBaseName.$sourceExtension"
 includeName="$headerSubDir/$headerFileName"
 
+sourceMakeFile="./src/Makefile.am"
+autAddComment="__AUTO_ADD_SOURCES_HERE__"
+
+getLastSourceFile()
+{
+	cat "$sourceMakeFile" |\
+		grep -B1 "#[[:space:]]*${autoAddComment}"	|\
+		grep -E "^[[:space:]]+$REGEXP_BASE_NAME\\.$sourceExtension[[:space:]]*\$" |\
+		sed -r 's/^[[:space:]]*(([[:alnum:]]|\.)+).*$/\1/'
+}
 
 for fileExtension in $fileExtensions
 do
@@ -149,10 +153,24 @@ do
 		targetDirectory="$headerDirectory"
 		targetFileName="$headerFileName"
 		sourceFile="$sourceTemplatesDirectory/header.hpp"
+		lastSourceFile=
+		autoAddSourceExpression=
 	else
 		targetDirectory="$sourceDirectory"
 		targetFileName="$sourceFileName"
 		sourceFile="$sourceTemplatesDirectory/source.cpp"
+		lastSourceFile=`getLastSourceFile`
+		if [[ "x" != "x$lastSourceFile" ]]
+		then
+			spaces="([[:space:]]+)";
+			lastSourceFilePastern="(`echo "$lastSourceFile" | sed -r 's/\./\\\./g'`)"
+			replacer1='\1\2 \\\n\1'
+			autoAddSourceExpression="s/^${spaces}${lastSourceFilePastern}.*\$/$replacer1$sourceFileName/"
+			echo "Auto-add: $autoAddSourceExpression"
+		else
+			echo "Skipping auto-add of source file to '$sourceMakeFile'"
+			get
+		fi
 	fi
 	targetFilePath="$targetDirectory/$targetFileName"
 
@@ -164,30 +182,39 @@ do
 
 	if ! mkdir -p "$targetDirectory"
 	then
-		echo "Could not create target directory '$targetDirectory'"
+		echo "Could not create target directory '$targetDirectory'" >&2
 		exit 1
 	fi
 
 	sourceFileNameExpr=`replaceExpression "templateFileName" "$targetFileName"`
 	headerFileNameExpr=`replaceExpression "templateInclude" "$includeName"`
 
-	echo "Generate: ${sourceFile} -> ${targetFilePath}"
-
-	cat "${sourceFile}" |\
-					sed -r "$projectNameExpr" |\
-					sed -r "$descriptionExpr" |\
-					sed -r "$headerSubDirExpr" |\
-					sed -r "$copyRightHolderExpr" |\
-					sed -r "$copyRightYearExpr" |\
-					sed -r "$emailAddressExpr" |\
-					sed -r "$contantsPrefixExpr" |\
-					sed -r "$nameSpaceExpr" |\
-					sed -r "$sourceRepositoryExpr" |\
-					sed -r "$copyRightNoticeExpr" |\
-					sed -r "$headerGuardNameExpr" |\
-					sed -r "$sourceExtensionExpr" |\
-					sed -r "$headerExtensionExpr" |\
-					sed -r "$sourceFileNameExpr" |\
-					sed -r "$headerFileNameExpr" \
-					> "$targetFilePath"
+	if cat "${sourceFile}" |\
+		sed -r "$projectNameExpr" |\
+		sed -r "$descriptionExpr" |\
+		sed -r "$headerSubDirExpr" |\
+		sed -r "$copyRightHolderExpr" |\
+		sed -r "$copyRightYearExpr" |\
+		sed -r "$emailAddressExpr" |\
+		sed -r "$contantsPrefixExpr" |\
+		sed -r "$nameSpaceExpr" |\
+		sed -r "$sourceRepositoryExpr" |\
+		sed -r "$copyRightNoticeExpr" |\
+		sed -r "$headerGuardNameExpr" |\
+		sed -r "$sourceExtensionExpr" |\
+		sed -r "$headerExtensionExpr" |\
+		sed -r "$sourceFileNameExpr" |\
+		sed -r "$headerFileNameExpr" \
+		> "$targetFilePath"
+	then
+		echo "Generated: ${sourceFile} -> ${targetFilePath}"
+		if [[ "x" != "x$autoAddSourceExpression" ]]
+		then
+			cp "${sourceMakeFile}" "${sourceMakeFile}~"
+			cat "${sourceMakeFile}~" | sed -r "$autoAddSourceExpression" >"${sourceMakeFile}"
+		fi
+	else
+		echo "Failed to generate: ${sourceFile} -> ${targetFilePath}" >&2
+		exit 1
+	fi
 done
